### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by MertHaddad** [ndom91/react-timezone-select#85]
### Describe the bug

Uncaught Error: Module parse failed: Unexpected token (9057:38)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.

### Reproduction

importing the module is enough.

### System Info

```Shell
W10 64 Chrome
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kjbeethov** [comment]
Same issue

**Comment by ndom91** [comment]
Can you give me some more details on your setup? Are you using "vanilla" `react` or a meta-framework like Next.js?

**Comment by ndom91** [comment]
Hey there's a lot of updates related to bundling / published version. 

Can you give the `latest` version on npm a shot?

**Comment by konstantsoftware** [comment]
I get the same error with latest installed

**Comment by ndom91** [comment]
Published a new version with some changes, including making `react-select` a peer dependency, can you try `react-timezone-select@2.0.0+`.

i.e.

```sh
npm install react-select react-timezone-select@2.0.0
```

**Comment by codeforcesmeme** [comment]
Is the error in this sandbox related to this one? It's an error in the dev server (react-scripts)

![image](https://user-images.githubusercontent.com/45147859/228626894-1cd0e791-2c30-4392-8a53-1cbd77727b80.png)

https://codesandbox.io/s/wonderful-franklin-15xbjq?file=/src/App.tsx

**Comment by ndom91** [comment]
> Is the error in this sandbox related to this one? It's an error in the dev server (react-scripts - when using v1.54+)
> 
> ![image](https://user-images.githubusercontent.com/45147859/228626894-1cd0e791-2c30-4392-8a53-1cbd77727b80.png)
> 
> [codesandbox.io/s/wonderful-franklin-15xbjq?file=/src/App.tsx](https://codesandbox.io/s/wonderful-franklin-15xbjq?file=/src/App.tsx)

I believe this is something else based on one of the recent PRs, should be fixed in `1.5.6` / `2.0.0` though

**Comment by nadnad** [comment]
Still seeing this with 2.1.0 when importing the TimezoneSelect component. The useTimezoneSelect hook import works fine though!

**Comment by ndom91** [comment]
Yeah worth trying.. I've updated the `tsconfig.json` target to `es6` in `v2.1.1` :+1:

**Comment by ndom91** [comment]
Let me know if that helped in any way :pray:

**Comment by milosDf** [comment]
Similar issue here:

![image](https://github.com/ndom91/react-timezone-select/assets/130058510/d3aab6ce-8589-452b-9cc2-3c5488514bb6)

I have:

`"react-select": "^5.7.7",
 "react-timezone-select": "^2.1.0",`

**Comment by ndom91** [comment]
Does anyone still see this issue with `2.1.1+`?

**Comment by danny-nguyen-lab49** [comment]
Yes I'm still experiencing this issue when running with nextjs. 

next: "^13.2.3"

`error - ./node_modules/react-select/node_modules/@babel/runtime/helpers/esm/classCallCheck.js
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export default function _classCallCheck(instance, Constructor) {
|   if (!(instance instanceof Constructor)) {
|     throw new TypeError("Cannot call a class as a function");

Import trace for requested module:
./node_modules/react-select/node_modules/@babel/runtime/helpers/esm/classCallCheck.js
./node_modules/react-select/dist/react-select.esm.js
./node_modules/react-timezone-select/dist/index.js
`

**Comment by ndom91** [comment]
@danny-nguyen-lab49 can you give `v3.0.3` a shot? I updated the `react-select` peer dependency to minimum version `5.7.3` where they apparently shipped a fix for ESM importing (https://github.com/JedWatson/react-select/releases/tag/react-select@5.7.3)

**Comment by ndom91** [comment]
Haven't heard back here, should be working now so I'm going to close this.

If anyone still has an issue, feel free to open a new issue
